# Generated by Django 4.2.1 on 2023-06-17 13:29

import director.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_user_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', director.models.user.CustomUserManager()),
            ],
        ),
    ]
